### ISSUE TITLE
applet@author: Bugkk

### ISSUE THREAD

**Issue by mtwebster** [mtwebster/cinnamon-spices-applets#2]
### Applet version/Build date

4.2

### Cinnamon version

5.6

### Distribution

Mint 21

### Graphics hardware *and* driver used

Nvidia

### Snippet or attachment of `~/.xsession-errors`

It's like this and like that and like this.

### Applet name and maintainer

better-backgrounds@simonmicro @simonmicro

### Relevant log output

```shell
Logging stuff...
```

### What happened?

okokkok

### Steps to reproduce

It didn't work

### Expected behaviour

Working shit

### Other information

More stuff

**Comment by simonmicro** [comment]
Yooo, what is going on?

**Comment by mtwebster** [comment]
Hi sorry about that! We were testing out the new bug form for the spices repos and I randomly chose your applet.

**Comment by simonmicro** [comment]
Ah, cool! No problem! :ok_hand:
